[2024-11-24T12:33:43.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T12:33:43.648+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T11:22:55+00:00 [queued]>
[2024-11-24T12:33:43.653+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T11:22:55+00:00 [queued]>
[2024-11-24T12:33:43.653+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-11-24T12:33:43.660+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-11-24 11:22:55+00:00
[2024-11-24T12:33:43.663+0000] {standard_task_runner.py:72} INFO - Started process 291 to run task
[2024-11-24T12:33:43.665+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'manual__2024-11-24T11:22:55+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmp7po2br5s']
[2024-11-24T12:33:43.667+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask collect_data
[2024-11-24T12:33:43.694+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T11:22:55+00:00 [running]> on host 28b55c2984f3
[2024-11-24T12:33:43.734+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T11:22:55+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T11:22:55+00:00'
[2024-11-24T12:33:43.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T12:33:43.746+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-24T12:33:43.746+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-11-24T12:33:43.751+0000] {subprocess.py:99} INFO - Output:
[2024-11-24T12:38:44.689+0000] {subprocess.py:106} INFO - Exception in thread Thread-2 (collect_all):
[2024-11-24T12:38:44.691+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-24T12:38:44.691+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
[2024-11-24T12:38:44.692+0000] {subprocess.py:106} INFO - Exception in thread Thread-1 (collect_all):
[2024-11-24T12:38:44.692+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-24T12:38:44.692+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
[2024-11-24T12:38:44.692+0000] {subprocess.py:106} INFO -     self.run()
[2024-11-24T12:38:44.693+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
[2024-11-24T12:38:44.693+0000] {subprocess.py:106} INFO -     self._target(*self._args, **self._kwargs)
[2024-11-24T12:38:44.694+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 72, in collect_all
[2024-11-24T12:38:44.696+0000] {subprocess.py:106} INFO -     self.run()
[2024-11-24T12:38:44.696+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
[2024-11-24T12:38:44.697+0000] {subprocess.py:106} INFO -     self._target(*self._args, **self._kwargs)
[2024-11-24T12:38:44.697+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 72, in collect_all
[2024-11-24T12:38:44.697+0000] {subprocess.py:106} INFO -     driver = webdriver.Remote(
[2024-11-24T12:38:44.697+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^
[2024-11-24T12:38:44.698+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-24T12:38:44.698+0000] {subprocess.py:106} INFO -     driver = webdriver.Remote(
[2024-11-24T12:38:44.698+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^
[2024-11-24T12:38:44.698+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -     self.start_session(capabilities)
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-11-24T12:38:44.699+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -     self.start_session(capabilities)
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-24T12:38:44.700+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO - selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO - Host info: host: '7a820e36699a', ip: '172.18.0.3'
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.11-linuxkit', java.version: '17.0.11'
[2024-11-24T12:38:44.701+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-11-24T12:38:44.702+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-11-24T12:38:44.702+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
[2024-11-24T12:38:44.702+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
[2024-11-24T12:38:44.703+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
[2024-11-24T12:38:44.703+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.703+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.704+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.704+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
[2024-11-24T12:38:44.705+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
[2024-11-24T12:38:44.705+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.705+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.705+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
[2024-11-24T12:38:44.706+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.707+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
[2024-11-24T12:38:44.708+0000] {subprocess.py:106} INFO -     at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO -     at java.util.concurrent.FutureTask.run (None:-1)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO -     at java.lang.Thread.run (None:-1)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO - selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out
[2024-11-24T12:38:44.709+0000] {subprocess.py:106} INFO - Host info: host: '7a820e36699a', ip: '172.18.0.3'
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.11-linuxkit', java.version: '17.0.11'
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
[2024-11-24T12:38:44.710+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.711+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.712+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T12:38:44.713+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
[2024-11-24T12:38:44.714+0000] {subprocess.py:106} INFO -     at java.util.concurrent.FutureTask.run (None:-1)
[2024-11-24T12:38:44.715+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
[2024-11-24T12:38:44.715+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
[2024-11-24T12:38:44.715+0000] {subprocess.py:106} INFO -     at java.lang.Thread.run (None:-1)
[2024-11-24T12:42:35.060+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-24T12:42:35.065+0000] {process_utils.py:132} INFO - Sending 15 to group 291. PIDs of all processes in the group: [293, 291]
[2024-11-24T12:42:35.066+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 291
[2024-11-24T12:42:35.068+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-24T12:42:35.071+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-11-24T12:42:35.092+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-24T12:42:35.105+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=manual__2024-11-24T11:22:55+00:00, execution_date=20241124T112255, start_date=20241124T123343, end_date=20241124T124235
[2024-11-24T12:42:35.121+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T12:42:35.165+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=293, status='terminated', started='12:33:43') (293) terminated with exit code None
[2024-11-24T12:42:35.166+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=291, status='terminated', exitcode=2, started='12:33:43') (291) terminated with exit code 2
[2024-11-24T12:42:35.167+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-24T12:42:35.204+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T12:42:38.604+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T12:42:38.613+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T11:22:55+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-11-24T12:42:38.613618+00:00 and task will be retried at 2024-11-24T12:47:35.100889+00:00.
[2024-11-24T12:42:38.614+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
