[2024-11-24T06:55:08.993+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T06:55:09.002+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T06:35:00.531064+00:00 [queued]>
[2024-11-24T06:55:09.007+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T06:35:00.531064+00:00 [queued]>
[2024-11-24T06:55:09.007+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-24T06:55:09.014+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-11-24 06:35:00.531064+00:00
[2024-11-24T06:55:09.016+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-11-24T06:55:09.019+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'manual__2024-11-24T06:35:00.531064+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmpv1m9i6xe']
[2024-11-24T06:55:09.020+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask collect_data
[2024-11-24T06:55:09.053+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T06:35:00.531064+00:00 [running]> on host 39b93340fe6b
[2024-11-24T06:55:09.099+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T06:35:00.531064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T06:35:00.531064+00:00'
[2024-11-24T06:55:09.099+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T06:55:09.111+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-24T06:55:09.112+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-11-24T06:55:09.117+0000] {subprocess.py:99} INFO - Output:
[2024-11-24T07:00:10.102+0000] {subprocess.py:106} INFO - Exception in thread Thread-2 (collect_all):
[2024-11-24T07:00:10.108+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-24T07:00:10.110+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
[2024-11-24T07:00:10.111+0000] {subprocess.py:106} INFO -     self.run()
[2024-11-24T07:00:10.112+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
[2024-11-24T07:00:10.114+0000] {subprocess.py:106} INFO -     self._target(*self._args, **self._kwargs)
[2024-11-24T07:00:10.115+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 72, in collect_all
[2024-11-24T07:00:10.115+0000] {subprocess.py:106} INFO -     driver = webdriver.Remote(
[2024-11-24T07:00:10.116+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^
[2024-11-24T07:00:10.116+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
[2024-11-24T07:00:10.117+0000] {subprocess.py:106} INFO -     self.start_session(capabilities)
[2024-11-24T07:00:10.117+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
[2024-11-24T07:00:10.117+0000] {subprocess.py:106} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-11-24T07:00:10.118+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-24T07:00:10.118+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-24T07:00:10.118+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-11-24T07:00:10.118+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-24T07:00:10.119+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-24T07:00:10.119+0000] {subprocess.py:106} INFO - selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out
[2024-11-24T07:00:10.119+0000] {subprocess.py:106} INFO - Host info: host: 'b54d672c0c7d', ip: '172.18.0.3'
[2024-11-24T07:00:10.119+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-11-24T07:00:10.119+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.11-linuxkit', java.version: '17.0.11'
[2024-11-24T07:00:10.120+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-11-24T07:00:10.120+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-11-24T07:00:10.120+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
[2024-11-24T07:00:10.121+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
[2024-11-24T07:00:10.121+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
[2024-11-24T07:00:10.121+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.121+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.122+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.122+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
[2024-11-24T07:00:10.122+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
[2024-11-24T07:00:10.122+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T07:00:10.123+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.123+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.123+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
[2024-11-24T07:00:10.123+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.124+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-11-24T07:00:10.125+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
[2024-11-24T07:00:10.126+0000] {subprocess.py:106} INFO -     at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
[2024-11-24T07:00:10.127+0000] {subprocess.py:106} INFO -     at java.util.concurrent.FutureTask.run (None:-1)
[2024-11-24T07:00:10.127+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
[2024-11-24T07:00:10.127+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
[2024-11-24T07:00:10.127+0000] {subprocess.py:106} INFO -     at java.lang.Thread.run (None:-1)
[2024-11-24T07:00:21.185+0000] {subprocess.py:106} INFO - Exception in thread Thread-1 (collect_all):
[2024-11-24T07:00:21.187+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-24T07:00:21.189+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
[2024-11-24T07:00:21.189+0000] {subprocess.py:106} INFO -     self.run()
[2024-11-24T07:00:21.190+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
[2024-11-24T07:00:21.190+0000] {subprocess.py:106} INFO -     self._target(*self._args, **self._kwargs)
[2024-11-24T07:00:21.190+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 81, in collect_all
[2024-11-24T07:00:21.192+0000] {subprocess.py:106} INFO -     page_data = collect_data_from_page(page_num, category_num, driver)
[2024-11-24T07:00:21.194+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-24T07:00:21.195+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 22, in collect_data_from_page
[2024-11-24T07:00:21.195+0000] {subprocess.py:106} INFO -     driver.get(page_url)
[2024-11-24T07:00:21.195+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 389, in get
[2024-11-24T07:00:21.196+0000] {subprocess.py:106} INFO -     self.execute(Command.GET, {"url": url})
[2024-11-24T07:00:21.196+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
[2024-11-24T07:00:21.197+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-11-24T07:00:21.197+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2024-11-24T07:00:21.197+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-11-24T07:00:21.197+0000] {subprocess.py:106} INFO - selenium.common.exceptions.WebDriverException: Message: Unable to execute request for an existing session: java.util.concurrent.TimeoutException
[2024-11-24T07:00:21.198+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-11-24T07:00:21.198+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.11-linuxkit', java.version: '17.0.11'
[2024-11-24T07:00:21.199+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-11-24T07:00:21.199+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-11-24T07:00:21.200+0000] {subprocess.py:106} INFO - java.lang.RuntimeException: Unable to execute request for an existing session: java.util.concurrent.TimeoutException
[2024-11-24T07:00:21.200+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-11-24T07:00:21.201+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.11-linuxkit', java.version: '17.0.11'
[2024-11-24T07:00:21.201+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-11-24T07:00:21.201+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:208)
[2024-11-24T07:00:21.202+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:383)
[2024-11-24T07:00:21.202+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.202+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.202+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.203+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
[2024-11-24T07:00:21.203+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
[2024-11-24T07:00:21.204+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
[2024-11-24T07:00:21.204+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.211+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.219+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
[2024-11-24T07:00:21.224+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.225+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.225+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.225+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.225+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.226+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.226+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.226+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.226+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.227+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
[2024-11-24T07:00:21.227+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
[2024-11-24T07:00:21.227+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
[2024-11-24T07:00:21.227+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
[2024-11-24T07:00:21.227+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
[2024-11-24T07:00:21.228+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
[2024-11-24T07:00:21.228+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2024-11-24T07:00:21.228+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[2024-11-24T07:00:21.228+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2024-11-24T07:00:21.228+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2024-11-24T07:00:21.229+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2024-11-24T07:00:21.229+0000] {subprocess.py:106} INFO - Caused by: java.util.concurrent.TimeoutException
[2024-11-24T07:00:21.229+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
[2024-11-24T07:00:21.229+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
[2024-11-24T07:00:21.229+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:379)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:352)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:90)
[2024-11-24T07:00:21.230+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.node.DefaultActiveSession.execute(DefaultActiveSession.java:62)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:126)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:628)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:383)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:87)
[2024-11-24T07:00:21.231+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
[2024-11-24T07:00:21.232+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:346)
[2024-11-24T07:00:21.232+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
[2024-11-24T07:00:21.232+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
[2024-11-24T07:00:21.232+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:55)
[2024-11-24T07:00:21.232+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:71)
[2024-11-24T07:00:21.233+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:90)
[2024-11-24T07:00:21.233+0000] {subprocess.py:106} INFO - 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:181)
[2024-11-24T07:00:21.233+0000] {subprocess.py:106} INFO - 	... 30 more
[2024-11-24T07:00:21.233+0000] {subprocess.py:106} INFO - 
[2024-11-24T07:15:09.032+0000] {timeout.py:68} ERROR - Process timed out, PID: 105
[2024-11-24T07:15:09.047+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-11-24T07:15:09.093+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 105
[2024-11-24T07:15:09.109+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=manual__2024-11-24T06:35:00.531064+00:00, execution_date=20241124T063500, start_date=20241124T065509, end_date=20241124T071509
[2024-11-24T07:15:09.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T07:15:09.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2024-11-24T07:15:09.176+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T07:15:09.177+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
